heads: 0.2.1-unstable-2025-04-03 -> 0.2.1-unstable-2026-02-01

diff --git a/pkgs/by-name/heads/2001-heads-Take-blobs-from-prefetched-blobsDir.patch.in b/pkgs/by-name/heads/2001-heads-Take-blobs-from-prefetched-blobsDir.patch.in
--- a/pkgs/by-name/heads/2001-heads-Take-blobs-from-prefetched-blobsDir.patch.in
+++ b/pkgs/by-name/heads/2001-heads-Take-blobs-from-prefetched-blobsDir.patch.in
@@ -1,19 +1,20 @@
-From 25b2199fe91f34f16914f40ac5ac6afa3201a0c4 Mon Sep 17 00:00:00 2001
+From df702f74fca2472b7adc5e8b8a3dc27f9cba4e93 Mon Sep 17 00:00:00 2001
 From: OPNA2608 <opna2608@protonmail.com>
-Date: Fri, 4 Apr 2025 17:07:31 +0200
+Date: Sun, 1 Feb 2026 09:52:10 +0100
 Subject: [PATCH] heads: Take blobs from prefetched blobsDir
 
 ---
- blobs/p8z77-m_pro/download_BIOS_clean.sh       | 3 ++-
- blobs/t440p/download-clean-me                  | 4 +++-
- blobs/w541/download-clean-me                   | 4 +++-
- blobs/xx20/download_parse_me.sh                | 3 ++-
- blobs/xx30/download_clean_me.sh                | 4 +++-
- blobs/xx30/download_clean_me_manually.sh       | 3 ++-
- blobs/xx30/optiplex_7010_9010.sh               | 7 ++++---
- blobs/xx80/download_clean_deguard_me_pad_tb.sh | 6 ++++--
- blobs/z220/download_BIOS_clean.sh              | 3 ++-
- 9 files changed, 25 insertions(+), 12 deletions(-)
+ blobs/p8z77-m_pro/download_BIOS_clean.sh           |  3 ++-
+ blobs/t440p/download-clean-me                      |  4 +++-
+ blobs/w541/download-clean-me                       |  4 +++-
+ blobs/xx20/download_parse_me.sh                    |  3 ++-
+ blobs/xx30/download_clean_me.sh                    |  4 +++-
+ blobs/xx30/download_clean_me_manually.sh           |  3 ++-
+ blobs/xx30/optiplex_7010_9010.sh                   | 14 +++++++-------
+ .../xx80/t480_download_clean_deguard_me_pad_tb.sh  |  6 ++++--
+ .../xx80/t480s_download_clean_deguard_me_pad_tb.sh |  6 ++++--
+ blobs/z220/download_BIOS_clean.sh                  |  3 ++-
+ 10 files changed, 32 insertions(+), 18 deletions(-)
 
 diff --git a/blobs/p8z77-m_pro/download_BIOS_clean.sh b/blobs/p8z77-m_pro/download_BIOS_clean.sh
 index 6f604106..fb4f3635 100755
@@ -103,7 +104,7 @@ index d7e44d01..442d704c 100755
  echo "$ME_EXE_SHA256SUM" | sha256sum --check || { echo "Failed sha256sum verification on downloaded binary..." && exit 1; }
  
 diff --git a/blobs/xx30/optiplex_7010_9010.sh b/blobs/xx30/optiplex_7010_9010.sh
-index 2b215248..f4cf2c28 100755
+index 20f71a84..f83c525e 100755
 --- a/blobs/xx30/optiplex_7010_9010.sh
 +++ b/blobs/xx30/optiplex_7010_9010.sh
 @@ -12,8 +12,8 @@ if [[ ! -f "${output_dir}/IVB_BIOSAC_PRODUCTION.bin" ]] || [[ ! -f "${output_dir
@@ -117,37 +118,74 @@ index 2b215248..f4cf2c28 100755
  
      #Extract binary
      binwalk -e O7010A29.exe -C . --run-as=root
-@@ -34,7 +34,8 @@ if [[ ! -f "${output_dir}/IVB_BIOSAC_PRODUCTION.bin" ]] || [[ ! -f "${output_dir
+@@ -32,17 +32,17 @@ if [[ ! -f "${output_dir}/IVB_BIOSAC_PRODUCTION.bin" ]] || [[ ! -f "${output_dir
+     mv IVB_BIOSAC_PRODUCTION.bin "${output_dir}/"
+ 
      #Download sinit
+-    if wget https://dl.3mdeb.com/mirror/intel/acm/SNB_IVB_SINIT_20190708_PW.bin -O "${output_dir}/SNB_IVB_SINIT_20190708_PW.bin"; then
+-      # As per https://github.com/Dasharo/dasharo-issues/issues/1283#issuecomment-3178940096 : use 3mdeb's intel mirror for sinit blob
++    if [ -f @blobsDir@/SNB_IVB_SINIT_20190708_PW.bin ]; then
++      cp -L --no-preserve=mode @blobsDir@/SNB_IVB_SINIT_20190708_PW.bin "${output_dir}/"
+       popd || exit
      # Original URL got rid of needed file, keeping original URL. Let's use archive.org
      #wget https://cdrdv2.intel.com/v1/dl/getContent/630744 -O sinit.zip
--    wget http://web.archive.org/web/20230712081031/https://cdrdv2.intel.com/v1/dl/getContent/630744 -O sinit.zip
-+    blobName="sinit.zip"
-+    cp -L --no-preserve=mode @blobsDir@/"$blobName" ./ || { echo "ERROR: Blob ${blobName} missing from blobsDir" && exit 1; }
-     unzip sinit.zip
-     mv 630744_002/SNB_IVB_SINIT_20190708_PW.bin "${output_dir}/" 
-     
-diff --git a/blobs/xx80/download_clean_deguard_me_pad_tb.sh b/blobs/xx80/download_clean_deguard_me_pad_tb.sh
-index 290ca416..347babf5 100755
---- a/blobs/xx80/download_clean_deguard_me_pad_tb.sh
-+++ b/blobs/xx80/download_clean_deguard_me_pad_tb.sh
+-    elif wget http://web.archive.org/web/20230712081031/https://cdrdv2.intel.com/v1/dl/getContent/630744 -O sinit.zip; then
+-      unzip sinit.zip
++    elif [ -f @blobsDir@/sinit.zip ]; then
++      unzip @blobsDir@/sinit.zip
+       mv 630744_002/SNB_IVB_SINIT_20190708_PW.bin "${output_dir}/"
+       popd || exit
+     else
+-      echo "Can't download sinit blob, failing"
++      echo "ERROR: blobsDir must have one of these: SNB_IVB_SINIT_20190708_PW.bin sinit.zip"
+       exit 1
+     fi
+ fi
+diff --git a/blobs/xx80/t480_download_clean_deguard_me_pad_tb.sh b/blobs/xx80/t480_download_clean_deguard_me_pad_tb.sh
+index 3bd83140..6da29d2f 100755
+--- a/blobs/xx80/t480_download_clean_deguard_me_pad_tb.sh
++++ b/blobs/xx80/t480_download_clean_deguard_me_pad_tb.sh
 @@ -60,7 +60,8 @@ function download_and_clean() {
  	# Download the installer that contains the ME blob
  	me_installer_filename="Inspiron_5468_1.3.0.exe"
  	user_agent="Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0"
 -	curl -A "$user_agent" -s -O "https://dl.dell.com/FOLDER04573471M/1/${me_installer_filename}"
-+  blobName="$(basename "https://dl.dell.com/FOLDER04573471M/1/${me_installer_filename}")"
-+  cp -L --no-preserve=mode @blobsDir@/"$blobName" ./ || { echo "ERROR: Blob ${blobName} missing from blobsDir" && exit 1; }
++	blobName="$(basename "https://dl.dell.com/FOLDER04573471M/1/${me_installer_filename}")"
++	cp -L --no-preserve=mode @blobsDir@/"$blobName" ./ || { echo "ERROR: Blob ${blobName} missing from blobsDir" && exit 1; }
  	chk_sha256sum "$ME_DOWNLOAD_HASH" "$me_installer_filename"
  
  	# Download the tool to unpack Dell's installer and unpack the ME blob.
-@@ -119,7 +120,8 @@ function download_and_pad_tb() {
+@@ -123,7 +124,8 @@ function download_and_pad_tb() {
  	# Download the installer that contains the TB blob
  	tb_installer_filename=""n24th13w.exe""
  	user_agent="Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0"
 -	curl -A "$user_agent" -s -O "https://download.lenovo.com/pccbbs/mobiles/${tb_installer_filename}"
-+  blobName="$(basename "https://download.lenovo.com/pccbbs/mobiles/${tb_installer_filename}")"
-+  cp -L --no-preserve=mode @blobsDir@/"$blobName" ./ || { echo "ERROR: Blob ${blobName} missing from blobsDir" && exit 1; }
++	blobName="$(basename "https://download.lenovo.com/pccbbs/mobiles/${tb_installer_filename}")"
++	cp -L --no-preserve=mode @blobsDir@/"$blobName" ./ || { echo "ERROR: Blob ${blobName} missing from blobsDir" && exit 1; }
+ 	chk_sha256sum "$TB_DOWNLOAD_HASH" "$tb_installer_filename"
+ 
+ 	# https://www.reddit.com/r/thinkpad/comments/9rnimi/ladies_and_gentlemen_i_present_to_you_the/
+diff --git a/blobs/xx80/t480s_download_clean_deguard_me_pad_tb.sh b/blobs/xx80/t480s_download_clean_deguard_me_pad_tb.sh
+index 0008cec8..63aad41d 100755
+--- a/blobs/xx80/t480s_download_clean_deguard_me_pad_tb.sh
++++ b/blobs/xx80/t480s_download_clean_deguard_me_pad_tb.sh
+@@ -61,7 +61,8 @@ function download_and_clean() {
+ 	# Download the installer that contains the ME blob
+ 	me_installer_filename="Inspiron_5468_1.3.0.exe"
+ 	user_agent="Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0"
+-	curl -A "$user_agent" -s -O "https://dl.dell.com/FOLDER04573471M/1/${me_installer_filename}"
++	blobName="$(basename "https://dl.dell.com/FOLDER04573471M/1/${me_installer_filename}")"
++	cp -L --no-preserve=mode @blobsDir@/"$blobName" ./ || { echo "ERROR: Blob ${blobName} missing from blobsDir" && exit 1; }
+ 	chk_sha256sum "$ME_DOWNLOAD_HASH" "$me_installer_filename"
+ 
+ 	# Download the tool to unpack Dell's installer and unpack the ME blob.
+@@ -124,7 +125,8 @@ function download_and_pad_tb() {
+ 	# Download the installer that contains the T480s TB blob
+ 	tb_installer_filename=""n22th11w.exe""
+ 	user_agent="Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0"
+-	curl -A "$user_agent" -s -O "https://download.lenovo.com/pccbbs/mobiles/${tb_installer_filename}"
++	blobName="$(basename "https://download.lenovo.com/pccbbs/mobiles/${tb_installer_filename}")"
++	cp -L --no-preserve=mode @blobsDir@/"$blobName" ./ || { echo "ERROR: Blob ${blobName} missing from blobsDir" && exit 1; }
  	chk_sha256sum "$TB_DOWNLOAD_HASH" "$tb_installer_filename"
  
  	# https://www.reddit.com/r/thinkpad/comments/9rnimi/ladies_and_gentlemen_i_present_to_you_the/
@@ -166,5 +204,5 @@ index b21ae3b2..dd5febf9 100755
  echo "$BIN_TGZ_SHA256SUM" | sha256sum --check || { echo "Failed sha256sum verification on downloaded binary..." && exit 1; }
  
 -- 
-2.47.2
+2.51.2
 
